apiVersion: autoscaling/v2beta1
kind: HorizontalPodAutoscaler
metadata:
 name: consumer-scaler
spec:
 scaleTargetRef:
   apiVersion: apps/v1
   kind: Deployment
   name: jmeter-master
 minReplicas: 1
 maxReplicas: 10
 metrics:
  - type: External
    external:
      metricName: cosmos
      targetValue: 5